#SPDX-License-Identifier: Unlicense
---
ca_host: localhost
ca_san:
  - DNS:ca.iana.org
  - email:user@iana.org
int_ca_path_crt: /etc/ssl/root/certs/ca.crt
int_ca_path_key: /etc/ssl/root/private/ca.key
int_dirs:
  - /etc/ssl/root/int/private
  - /etc/ssl/root/int/certs
  - /etc/ssl/root/int/csr
  - /etc/ssl/root/int
int_path_key: /etc/ssl/root/int/private/int.key
int_path_crt: /etc/ssl/root/int/certs/int.crt
int_path_csr: /etc/ssl/root/int/csr/int.csr
int_san:
  - DNS:int.iana.org
  - email:user@iana.org
