---
- name: sign | Generate Private Key
  community.crypto.openssl_privatekey:
    path: >-
      {{ sign_path_key }}
    size: 4096
    type: RSA

- name: sign | Ensure ssl directories
  ansible.builtin.file:
    dest: >-
      {{ item }}
    state: directory
    owner: root
    group: root
    mode: ug+rwx,o-rwx
  loop: >-
    {{ sign_dirs }}

- name: sign | Generate CSR
  community.crypto.openssl_csr:
    common_name: >-
      {{ sign_common_name }}
    group: root
    mode: >-
      ug+rw
    owner: root
    path: >-
      {{ sign_path_csr }}
    privatekey_path: >-
      {{ sign_path_key }}
    subject_alt_name: >-
      {{ item }}
  loop:
    - >-
      {{ sign_int_san }}
    - >-
      {{ sign_ca_san }}
    - >-
      {{ sign_cert_san }}

- name: sign | Sign Certificate
  community.crypto.x509_certificate:
    privatekey_path: >-
      {{ sign_path_key }}
    csr_path: >-
      {{ sign_path_csr }}
    ownca_path: >-
      {{ sign_int_path_crt }}
    ownca_privatekey_path: >-
      {{ sign_int_path_key }}
    provider: ownca
    path: >-
      {{ sign_path_crt }}
  register: certificate

- name: sign | Output certificate
  debug:
    var: certificate
