---
- name: Create root CA
  hosts: ca.breeze-blocks.net
  remote_user: duchess
  become: true
  roles:
    - role: ca
      tags:
        - ca
        - private_key
- name: Create int CA
  hosts: ca.breeze-blocks.net,int.breeze-blocks.net
  remote_user: duchess
  become: true
  roles:
    - role: int
      tags:
        - int
    - role: sign
      tags:
        - sign
