---
- name: Create root CA
  hosts: localhost
  become: true
  roles:
    - role: ca
      tags:
        - ca
        - private_key
      vars:
        ca_email: user@domain.com
        ca_locality: Los Angeles
        ca_org: IANA
        ca_org_unit: Engineering
        ca_san:
          - DNS:iana.domain.com
          - email:user@domain.com
        ca_state: California
- name: Create int CA
  hosts: localhost
  become: true
  roles:
    - role: int
      tags:
        - int
    - role: sign
      tags:
        - sign
