  ###
  # ```{rubric} Clean
  # ```
  # ---
  # Clean existing directories.
- name: ca | Clean
  ansible.builtin.file:
    state: absent
    dest: "{{ item }}"
  loop: "{{ ca_paths }}"
  tags:
    - clean

- name: ca | Install opnessl
  community.general.pacman:
    name: openssl
    state: present
    update_cache: true
  tags:
    - private_key
    - ca

- name: ca | Add directories
  ansible.builtin.file:
    state: directory
    group: root
    owner: root
    dest: "{{ item }}"
    mode: 'u+rw,g+rw,o+r'
  loop: >-
    {{ ca_ssl_dirs }}
  tags:
    - ca

- name: ca | Create private key with password protection
  community.crypto.openssl_privatekey:
    path: "{{ ca_paths.2 }}"
  tags:
    - private_key
    - ca

- name: ca | Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    common_name: "{{ inventory_hostname }}"
    country_name: US
    email_address: "{{ ca_email }}"
    key_usage:
      - keyCertSign
    key_usage_critical: true
    locality_name: Los Angeles
    organization_name: "{{ ca_org }}"
    organizational_unit_name: "{{ ca_org_unit }}"
    privatekey_path: "{{ ca_paths.2 }}"
    subject_alt_name: "{{ ca_san }}"
    state_or_province_name: California
    use_common_name_for_san: false
  register: ca_csr
  tags:
    - ca

- name: ca | Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ ca_paths.3 }}"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ ca_paths.2 }}"
    provider: selfsigned
  tags:
    - ca
