#SPDX-License-Identifier: Unlicense
---
sign_ca_san:
  - DNS:ca.iana.org
  - email:user@iana.org
sign_cert_san:
  - DNS:cert.iana.org
  - email:user@iana.org
sign_common_name: cert.iana.org
sign_int_path_crt: /etc/ssl/root/int/certs/int.crt
sign_int_path_key: /etc/ssl/root/int/private/int.key
sign_int_san:
  - DNS:int.iana.org
  - email:user@iana.org
sign_paths:
  - /etc/ssl/certs/
  - /etc/ssl/csr/
  - /etc/ssl/private/
sign_path_crt: /etc/ssl/certs/iana.crt
sign_path_csr: /etc/ssl/csr/iana.csr
sign_path_key: /etc/ssl/private/iana.key
