###
# SPDX-License-Identifier: Unlicense
#
# ```{rubric} Ansible Galaxy CA Role
# ```
# ---
# Author, description et cetera.
galaxy_info:
  author: xander harris
  description: generate a self-signed certificate authority
  company: the harris

  ###
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: https://github.com/edwardtheharris/ansible-ca/issues

  ###
  # Choose a valid license ID from
  # https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: Unlicense

  ###
  # Minimum usable Ansible version
  min_ansible_version: >-
    2.18

  ###
  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:
  #
  # List tags for your role here, one per line. A tag is a keyword that describes
  # and categorizes the role. Users find roles by searching for tags. Be sure to
  # remove the '[]' above, if you add tags to this list.
  #
  # ```{note}
  # A tag is limited to a single word comprised of alphanumeric characters.
  #
  # Maximum 20 tags per role.
  # ```
  galaxy_tags:
    - ssl
    - certificate
    - authority

###
# ```{rubric} Dependencies
# ```
# ---
# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
#
# ```{literalinclude} /roles/ca/meta/main.yml
# :language:
# :start-at: "dependencies: []"
# ```
dependencies: []
